# Generated by Django 4.0.2 on 2022-02-08 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='discription',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='course',
            name='name',
        ),
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(default='course_defualt.jpg', upload_to='images/course'),
        ),
        migrations.AddField(
            model_name='course',
            name='title',
            field=models.CharField(default='hello', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chapter',
            name='name',
            field=models.CharField(max_length=256),
        ),
    ]
