# Generated by Django 4.0.2 on 2022-02-09 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_course_subtitle_alter_course_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='description',
            new_name='detail',
        ),
    ]
