# Generated by Django 4.0.2 on 2022-02-09 17:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_alter_course_detail_alter_course_subtitle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='date_published',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=127),
        ),
    ]
