# Generated by Django 4.0.2 on 2022-02-14 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_alter_lesson_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='payment_status',
            field=models.CharField(choices=[('free', 'Free'), ('paid', 'Paid')], default='paid', max_length=4),
        ),
    ]
