# Generated by Django 4.0.2 on 2022-02-15 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0012_remove_course_image_course_promotion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(default='course.jpg', upload_to='images/courses'),
        ),
    ]
