# Generated by Django 4.0.2 on 2022-02-15 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0013_course_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='promotion',
            field=models.FileField(upload_to='videos/courses/'),
        ),
    ]
