# Generated by Django 4.0.2 on 2022-02-17 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0014_alter_course_promotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='payment_status',
            field=models.CharField(choices=[('free', 'Free'), ('paid', 'Paid')], default='paid', max_length=4),
        ),
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, default=99.99, max_digits=5),
        ),
    ]
